### ISSUE TITLE
Need concise compilation instructions for Ubuntu 16.x

### ISSUE THREAD

**Issue by tstrike34** [xsacha/Sachesi#100]
Various packages are being substituted in this version of Ubuntu. Using the Ubuntu 14.x compilation instructions are outdated for Ubuntu 16.x.

**Comment by xsacha** [comment]
I am unsure of the specific package names but essentially you just need Qt5 and libusb.

**Comment by JDJoe** [comment]
you need to remove qtdeclarative5-controls-plugin, qtdeclarative5-dialogs-plugin qtdeclarative5-quicklayouts-plugin and run:

$ sudo apt-get install qt5-qmake libqt5network5 libqt5qml5 qtdeclarative5-settings-plugin qtdeclarative5-window-plugin qtdeclarative5-qtquick2-plugin qttools5-dev-tools libssl-dev qtdeclarative5-dev libusb-1.0-0-dev

make sure you have libudev-dev installed too

**Comment by xsacha** [comment]
Thanks @JDJoe
