### ISSUE TITLE
lrelease: could not find a Qt installation of ''

### ISSUE THREAD

**Issue by m4er** [xsacha/Sachesi#105]
I try to install Sachesi on Ubuntu 17.10 & I'm getting this error (I'm a total noob & I don't know anything about compiling stuff):
ubuntu@ubuntu:~/Sachesi$ make
lrelease translations/Chinese.ts
lrelease: could not find a Qt installation of ''
Makefile:851: recipe for target 'translations/Chinese.qm' failed
make: *** [translations/Chinese.qm] Error 1

**Comment by xsacha** [comment]
Run qmake
