### ISSUE TITLE
build issue on macOS

### ISSUE THREAD

**Issue by L1cardo** [xsacha/Sachesi#112]
when I build the latest version on macOS, I can not build ！
can not found opensssl

<img width="936" alt="屏幕快照2019-06-11上午12 45 43" src="https://user-images.githubusercontent.com/33802186/59211475-80b92d80-8be2-11e9-9a8d-95148d00d9c0.png">

**Comment by L1cardo** [comment]
I don't know how to fix it.
Can you build a Mac version please！

**Comment by xsacha** [comment]
You need to have openssl development headers. Install openssl off the official website to get these.

I do have a Mac version but it may be too old because the platform moves pretty quick. https://github.com/xsacha/Sachesi/releases/download/2.0.2/Sachesi2.0.2-OSX.zip

**Comment by L1cardo** [comment]
I don’t know too much about coding, so it will be difficult for me to fix the issue.
OpenSSL doesn’t have a compiled version for Mac, i don’t know what to do and I have installed OpenSSL through homebrew, what should I do next?

**Comment by xsacha** [comment]
Try these instructions:
https://medium.com/@timmykko/using-openssl-library-with-macos-sierra-7807cfd47892

**Comment by L1cardo** [comment]
I am done with it ! One after another !
There is too many problem with the 2.0.3 version ,so I wanted to build a 2.0.4 version . but now I quit .
I don't know much about coding or compiling, I am just a normal user. it is not easy for me to solve the problem.

<img width="434" alt="屏幕快照2019-06-11上午9 00 34" src="https://user-images.githubusercontent.com/33802186/59236211-baf8ee00-8c27-11e9-9bca-383d825ff569.png">

**Comment by xsacha** [comment]
That's the same problem. It can't find your OpenSSL library. You need to tell it where it is if it isn't in a standard location.
You use the -L flag in the same way you used the -I flag.

**Comment by L1cardo** [comment]
I don't know how but finally I have built it. but there is no any translation !

![屏幕快照 2019-06-12 下午7 50 57](https://user-images.githubusercontent.com/33802186/59349114-6d75a180-8d4b-11e9-9628-5900dc957b05.png)

**Comment by xsacha** [comment]
It should have automatic translations based on your locale.
Which language?

**Comment by L1cardo** [comment]
> It should have automatic translations based on your locale.
> Which language?

It should be Chinese. But it is English and there is no language switch button.

**Comment by xsacha** [comment]
It's meant to work on your systems language. There's no switch for it. It's a Qt thing.

**Comment by L1cardo** [comment]
> It's meant to work on your systems language. There's no switch for it. It's a Qt thing.

My system language is Chinese.

**Comment by L1cardo** [comment]
@xsacha Can you build a macOS version for me please, I will be grateful!
Thanks!

**Comment by xsacha** [comment]
I don't think it'd be any different to the one you have.

I'd have to install macos or run it in a VM (which is how I made the other versions) and then set it up.

**Comment by L1cardo** [comment]
For now I have two issues , I am wondering if there was something wrong with my build 
1.The version 2.0.3 that you built works on macOS10.15 only a few crashes, but version 2.0.4 can not work on macOS10.15.
2.The version 2.0.3 that you built has a language switch button , but 2.0.4 doesn't .

<img width="819" alt="203" src="https://user-images.githubusercontent.com/33802186/59548389-41dbfc80-8f81-11e9-977e-3fb8f99e68cd.png">

![204](https://user-images.githubusercontent.com/33802186/59548395-53bd9f80-8f81-11e9-9159-974e2068ec80.png)

**Comment by xsacha** [comment]
Oh that is strange. I don't remember ever seeing this language switch.. and I compiled it!
Possibly you need to run a special qmake command to generate the languages?
