### ISSUE TITLE
Playbook Bootrom, MLO, Bootloader

### ISSUE THREAD

**Issue by bb10root** [xsacha/Sachesi#119]
Hello, could you please share the bootrom, mlo, etc.?
https://forums.crackberry.com/blackberry-playbook-os-f228/playbook-bootrom-mlo-bootloader-830909/

**Comment by xsacha** [comment]
It has been posted before and was taken down. I had it on mega (now deleted) and Google Drive. Will take me a while to find it again.
Is it for something important?

**Comment by bb10root** [comment]
Thanks for the quick response.
I would like to try to get root or learn how to change the firmware. The interest is more of an academic one.
About 13 years ago I was researching blackberry v5-7, but destroyed all the work. Now I have some free time and some BB10 phones and want to go back to research.
If you will have a chance to look for these files, it would be great. If not, that's okay.
And thank you for Sachesi, it is very helpful in research.

**Comment by xsacha** [comment]
@alexhude should be able to help you there if he's free.
