### ISSUE TITLE
will not connect to device with archlinux

### ISSUE THREAD

**Issue by badtoyz** [xsacha/Sachesi#26]
Sachesi sees the device but will not connect to it for backup or install. I have tried mac/windows options and put it in dev mode and still will not connect. I have also thought there could be a problem with systemd renaming the usb device so i made a rule and forced it to usb0. Any help would be great

**Comment by petr-fischer** [comment]
Hello, I have similar problem, when I run:

$ sudo dhcpcd -B enp0s20u2

output:
enp0s20u2: adding address fe80::b37d:8039:e9d6:6bab
enp0s20u2: waiting for carrier
enp0s20u2: carrier acquired
DUID 00:01:00:01:1d:30:6d:08:30:3a:64:7d:8b:c9
enp0s20u2: IAID 24:26:e4:6c
enp0s20u2: soliciting an IPv6 router
enp0s20u2: rebinding lease of 169.254.0.2
enp0s20u2: probing static address 169.254.0.2/30
enp0s20u2: leased 169.254.0.2 for 604800 seconds
enp0s20u2: adding route to 169.254.0.0/30
enp0s20u2: adding host route to 169.254.0.1
enp0s20u2: removing route to 169.254.0.0/30
enp0s20u2: no IPv6 Routers available

But ifconfig showing no IP address :(
enp0s20u2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b37d:8039:e9d6:6bab  prefixlen 64  scopeid 0x20<link>
        ether 4a:9d:24:26:e4:6c  txqueuelen 1000  (Ethernet)
        RX packets 39  bytes 22658 (22.1 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 89  bytes 37284 (36.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

So, no IP assigned to device enp0s20u2. What's wrong please?
