### ISSUE TITLE
Blank Windows on XP

### ISSUE THREAD

**Issue by machado7** [xsacha/Sachesi#57]
I have an old XP pc and Sachesi won't run if you don't create a folder called "Platforms" and add the "qwindows.dll" file. After that, Sachesi runs but nothing is displayed.
For the person who created the XP file, please try to deploy it again :)
![sachesi](https://cloud.githubusercontent.com/assets/8001614/7277640/640c1c76-e8ce-11e4-897f-1e7d105c7d00.JPG)

**Comment by xsacha** [comment]
Thanks for this info. Hopefully the person who builds WinXP builds will fix this. I can't maintain WinXP anymore as it involves maintaining a second set of dev tools.
