### ISSUE TITLE
Sachesi2.0.1-Windows won't start. MSVCR120.dll is missing.

### ISSUE THREAD

**Issue by vDorst** [xsacha/Sachesi#62]
Sachesi2-RC-Windows works oke and also has a lot less files included.

Sachesi2.0.1-Windows won't start. MSVCR120.dll is missing.

Running: Win 8.1 Pro [Version 6.3.9600] 64-bit.

**Comment by vDorst** [comment]
Solvution for me was installing [Visual C++ Redistributable Packages for Visual Studio 2013](http://www.microsoft.com/en-us/download/details.aspx?id=40784) *32-bit* version. 

Maybe should be added as a note in Readme.

**Comment by vDorst** [comment]
Please add a note in the Readme.

**Comment by xsacha** [comment]
This is specific to 2.0.1 so I've added a note to that release page. I'll use your link too. Thanks.
