### ISSUE TITLE
Missing Dependency on MAC

### ISSUE THREAD

**Issue by sanglt** [xsacha/Sachesi#63]
I can't run new version on my MAC. 2.0.0 is fine.
![screen shot 2015-06-19 at 8 12 18 am](https://cloud.githubusercontent.com/assets/128535/8245617/048760e8-165b-11e5-8725-5ca1b013295d.png)

**Comment by xsacha** [comment]
Thanks! I'll try to fix

**Comment by xsacha** [comment]
This should be fixed now. If not, reopen.
