### ISSUE TITLE
System Error - MSVCP.dll is missing 

### ISSUE THREAD

**Issue by williamrjribeiro** [xsacha/Sachesi#66]
I get the following System Error message on a popup when I try to run Sachesi 2.0.2 on a fresh install of Windows 10 Pro Insider Preview Build 10162:
"The program can't start because MSVCP120.dll is missing from your computer. Try reinstalling the program to fix this problem".

Can anyone check if it also happens on another version of Windows?

**Comment by xsacha** [comment]
Those errors will happen on all Windows. It is saying msvc 2013 redistributable x86 isn't installed.
I guess I missed a DLL.
I will correct in next version, thanks! You are first one to tell me :p

**Comment by williamrjribeiro** [comment]
Hum, I see the " msvcr120.dll" file next to "Sachesi.exe" and I have installed the "vcredist_x64" but it still doesn't work. Strange.

**Comment by xsacha** [comment]
Yeah it needs to be x86 version because the binary is 32-bit. Not related
to your system being x64.
Looks like there is two DLLs I needed to include (msvcr and msvcp).
