### ISSUE TITLE
[Arch] Sachesi downloads files in /usr/bin

### ISSUE THREAD

**Issue by Scellow** [xsacha/Sachesi#67]
Hello

I installed the sachesi-bin package

It works fine but it downloads files in the /usr/bin folder

**Comment by 69goat** [comment]
My guess from looking at the pkgbuild is that is because the Sachesi exe is installed to /usr/bin/ and Sachesi downloads to the folder it is in.  You can move the exe, but you will have to edit the .desktop file also.

**Comment by xsacha** [comment]
I think this is fixed in latest git (note: not compiled yet). If not, please suggest a change.
