### ISSUE TITLE
Required File Missing - Windows 10

### ISSUE THREAD

**Issue by barbarza** [xsacha/Sachesi#70]
Hi

I am trying to run the program in Windows 10 but I get an error saying that the program can't start because MSVCP120.dll is missing from the computer.

Please assist.

**Comment by thurask** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=40784

download vcredist_x86.exe, install, try again

**Comment by barbarza** [comment]
Brilliant! Thanks for the speedy response :)

**Comment by bb010g** [comment]
If @thurask's answer fixed your issue, please close.

**Comment by xsacha** [comment]
This file should be included with the latest version. If you ever have a latest version that doesn't include this, open the bug report again.
This is just to save people doing an extra download if they haven't already.
