### ISSUE TITLE
not working under windows 10

### ISSUE THREAD

**Issue by Unixware** [xsacha/Sachesi#71]
Displaying "Searching for USB devices" "talking to 2 possible devices" (same message when the Q5 is or not connected). Worked in win7/win8

**Comment by bakulkrishana** [comment]
It is working for me. It is not a problem of Sachesi, it is with the drivers of BB. I had to reconnect my device and it worked.

**Comment by xsacha** [comment]
Can you give more information if this issue is persisting? For example, IP address and Sachesi log?
