### ISSUE TITLE
How to create a .signed file?

### ISSUE THREAD

**Issue by Wesley-Chan** [xsacha/Sachesi#72]
I extracted the .bar files from the .signed file. But how do I put them back? I can only find a button for creating .exe file.

**Comment by xsacha** [comment]
We can't create signed files. Each file is signed by an unknown key, the
result of which is dropped during extraction.

**Comment by Wesley-Chan** [comment]
That means, I can't extract the official autoloader and add/remove what I like/hate and repack them and load it in my BB?

**Comment by thurask** [comment]
Nope.

Signed files aren't editable.

**Comment by Wesley-Chan** [comment]
Thanks.
