### ISSUE TITLE
Downloading files from BB servers indicates over 100%

### ISSUE THREAD

**Issue by polytan02** [xsacha/Sachesi#73]
A picture is always better than a long text : 

![screen shot 08-13-15 at 03 13 pm 001](https://cloud.githubusercontent.com/assets/7815185/9252017/2581ca60-41ce-11e5-80c0-0ccd5b716339.PNG)

**Comment by polytan02** [comment]
Actually, the downloading was blocked on this file in an infinite loop.

I unselected it from the list to be able to continue retrieving files. Strange.

**Comment by xsacha** [comment]
They blocked the carrier-specific 'bell' file? That is interesting!
Can you tell me what the MCC/MNC you used was and which firmware you were
downloading so I can replicate?
I will have a solution for blocked files then.

**Comment by polytan02** [comment]
MCC : 302 (Canada)
MNC : 640 (Bell)

I was on 10.3.2.2204 and I did a upgrade (non destructuve) via your app to 10.3.2.2339.

Great app by the way ;)

**Comment by xsacha** [comment]
I think possibly fixed in latest commit. I didn't get exactly the same issue as you but similar.
