### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by DLewis13** [xsacha/Sachesi#81]
Still looking for Windows version of 2.03.

Thanks for the great work xsacha,
Dick Lewis

**Comment by xsacha** [comment]
Was just waiting on a new Qt release. Should be able to push one out now.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: DLewis13Sent: Thursday, 15 October 2015 12:51 AMTo: xsacha/SachesiReply To: xsacha/SachesiSubject: [Sachesi] Windows version (#81)Still looking for Windows version of 2.03.

Thanks for the great work xsacha,
Dick Lewis

—Reply to this email directly or view it on GitHub.

**Comment by ModeenF** [comment]
Any news?

**Comment by Calvin413** [comment]
I am using Windows 10. My A/V keeps quaranteinig‎ one of the qt files. I have backed down to version 2.0.1 and it runs fine. I still have not seen a new version for Windows that I can run successfully.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: ModeenFSent: Tuesday, December 1, 2015 14:09To: xsacha/SachesiReply To: xsacha/SachesiSubject: Re: [Sachesi] Windows version (#81)Any news?

—Reply to this email directly or view it on GitHub.

**Comment by xsacha** [comment]
Windows version was released.
