### ISSUE TITLE
Trojan Virus

### ISSUE THREAD

**Issue by tabackd** [xsacha/Sachesi#84]
Hi I cannot use Sachesi as it has a trojan as per image

![image](https://cloud.githubusercontent.com/assets/16347309/11891650/551addb2-a569-11e5-8f8a-9adb504a7c16.png)

**Comment by xsacha** [comment]
Your antivirus is detecting 7zip compression as a virus. It will do this with any 7zip.
You should probably get a different antivirus that doesn't detect compression formats.
