### ISSUE TITLE
ubuntu 15.10

### ISSUE THREAD

**Issue by alianon** [xsacha/Sachesi#88]
it never connects i just get this message ," detected 1 blackberry usb device(s) in autodetec mode". and it just spins forever ,i have a passport sqw 100-1 but i dont have the option to switch from auto,windows,mac i only have the option to choose manual usb ip , please help because windows in vmware is way too slow to even use and i hate windows anyway.

**Comment by xsacha** [comment]
Does it work in Windows / have you tried it?
Is the device is Development Mode with password entered in to Sachesi?

**Comment by xsacha** [comment]
See #90 for solution. It probably has no IP address associated with it in Linux, so need dhclient.
