### ISSUE TITLE
Translation source files are gitignored?

### ISSUE THREAD

**Issue by cookiengineer** [xsacha/Sachesi#91]
See [gitignore#L26](https://github.com/xsacha/Sachesi/blob/master/.gitignore#L26) file.

The problem with the build setup is that the raw files (qm is the source format) are not tracked in git.
Therefore all the `RCC: Error in 'translations.qrc': Cannot find file '/translations/English.qm'` errors are a result of that.

Are the ts or the qm files the relevant source files for this repository?
I'm not getting how the `translations.qrc` file works as qmake step requires the `qm` files, but only the Makefile later seems to generate them!?

**Comment by xsacha** [comment]
Hi,
In Qt, qm files are generated from the rd files. Generated files shouldn't be included in the source control. Qt should be running this prior to build.
Tested here, it builds from clean, which is how all platform released are built.

**Comment by cookiengineer** [comment]
Okay, then I interpreted it correctly. As already merged, this issue is fixed then :)
